name: Commit

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    # Skip if the commit has more than one parent (merge commits have 2+ parents)
    if: ${{ github.event.pull_request.merged != true && github.event.head_commit.parents.length == 1 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run entry CI script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.sha }}
        run: bun scripts/ci/entry.ci.ts
